Resources:
  AccountRequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.accountRequestTable}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
